In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv("C:\\Users\\Pratham Chauhan\\furniture.csv")

# Separating the dependent and independent dataset
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 4].values



In [23]:
dataset

furniture_length  furniture_width  furniture_height  furniture_diagonal  \
0                 5.1              3.5               1.4                 0.2   
1                 4.9              3.0               1.4                 0.2   
2                 4.7              3.2               1.3                 0.2   
3                 4.6              3.1               1.5                 0.2   
4                 5.0              3.6               1.4                 0.2   
..                ...              ...               ...                 ...   
145               6.7              3.0               5.2                 2.3   
146               6.3              2.5               5.0                 1.9   
147               6.5              3.0               5.2                 2.0   
148               6.2              3.4               5.4                 2.3   
149               5.9              3.0               5.1                 1.8   

    furniture  
0        desk  
1        desk  
2        desk  
3        desk  
4        desk  
..        ...  
145     table  
146     table  
147     table  
148     table  
149     table  

[150 rows x 5 columns]

In [24]:
y

array(['desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk',
       'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk',
       'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk',
       'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk',
       'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk',
       'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk', 'desk',
       'desk', 'desk', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'chair', 'chair', 'chair', 'chair',
       'chair', 'chair', 'chair', 'table', 'table', 'table', 'table',
       'table', 

In [25]:
# Dividing the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

# Perform feature scaling before applying KNN classification.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# From sklearn import KNN technique

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Evaluate the performance of the model

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)


Confusion Matrix:
[[25  0  1]
 [ 0 18  0]
 [ 1  0 15]]
Classification Report:
              precision    recall  f1-score   support

       chair       0.96      0.96      0.96        26
        desk       1.00      1.00      1.00        18
       table       0.94      0.94      0.94        16

    accuracy                           0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60

Accuracy: 0.9666666666666667
