In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("C:\\Users\\Pratham Chauhan\\Jupyter\\Data.csv")

In [3]:
a=dataset.iloc[2,1]
a

30.0

In [4]:
x = dataset.iloc[2,-4]

In [5]:
x

'Germany'

In [6]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
a = dataset.iloc[1:5,0:]

In [8]:
a

Country   Age   Salary Purchased
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [23]:
x =dataset.iloc[: , : 3]
y=dataset.iloc[: , 3]

In [24]:
x 

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [25]:
y 

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [26]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values = np.nan , strategy ='mean')
imputer = imputer.fit(x.iloc[: , 1:])
x.iloc[:,1:] = imputer.transform(x.iloc[: ,1:])

In [13]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelencoder_x = LabelEncoder()
x.iloc[: , 0] = labelencoder_x.fit_transform(x.iloc[: , 0])

In [14]:
x

Country        Age        Salary
0        0  44.000000  72000.000000
1        2  27.000000  48000.000000
2        1  30.000000  54000.000000
3        2  38.000000  61000.000000
4        1  40.000000  63777.777778
5        0  35.000000  58000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
8        1  50.000000  83000.000000
9        0  37.000000  67000.000000

In [15]:
onehotencoder= OneHotEncoder()
data = x.iloc[: ,0]
data = data.to_numpy()


In [16]:
data

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [17]:
data = data.reshape(10,1)

In [18]:
data

array([[0],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0]])

In [19]:
x1 = onehotencoder.fit_transform(data).toarray()

In [20]:
x1 

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [21]:
x1.shape

(10, 3)

In [27]:
OH_encoder = OneHotEncoder(sparse=False)

In [30]:
x1=x['Country'].to_numpy().reshape(-1,1)

In [33]:
OH_cols_train=pd.DataFrame(OH_encoder.fit_transform(x1))

In [34]:
OH_cols_train

0    1    2
0  1.0  0.0  0.0
1  0.0  0.0  1.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0
5  1.0  0.0  0.0
6  0.0  0.0  1.0
7  1.0  0.0  0.0
8  0.0  1.0  0.0
9  1.0  0.0  0.0

In [35]:
x.drop('Country',axis=1,inplace=True)

In [36]:
x=pd.concat([x,OH_cols_train], axis=1)

In [37]:
x

Age        Salary    0    1    2
0  44.000000  72000.000000  1.0  0.0  0.0
1  27.000000  48000.000000  0.0  0.0  1.0
2  30.000000  54000.000000  0.0  1.0  0.0
3  38.000000  61000.000000  0.0  0.0  1.0
4  40.000000  63777.777778  0.0  1.0  0.0
5  35.000000  58000.000000  1.0  0.0  0.0
6  38.777778  52000.000000  0.0  0.0  1.0
7  48.000000  79000.000000  1.0  0.0  0.0
8  50.000000  83000.000000  0.0  1.0  0.0
9  37.000000  67000.000000  1.0  0.0  0.0

In [38]:
x=x.rename(columns={0:"France",1:"Germany",2:"Spain"})

In [39]:
x

Age        Salary  France  Germany  Spain
0  44.000000  72000.000000     1.0      0.0    0.0
1  27.000000  48000.000000     0.0      0.0    1.0
2  30.000000  54000.000000     0.0      1.0    0.0
3  38.000000  61000.000000     0.0      0.0    1.0
4  40.000000  63777.777778     0.0      1.0    0.0
5  35.000000  58000.000000     1.0      0.0    0.0
6  38.777778  52000.000000     0.0      0.0    1.0
7  48.000000  79000.000000     1.0      0.0    0.0
8  50.000000  83000.000000     0.0      1.0    0.0
9  37.000000  67000.000000     1.0      0.0    0.0

In [40]:
xnew=dataset.iloc[:,:-1]
ynew = dataset.iloc[: , :-1]   

In [42]:
xnew = pd.get_dummies(xnew)

In [43]:
xnew

Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0               1                0              0
1  27.0  48000.0               0                0              1
2  30.0  54000.0               0                1              0
3  38.0  61000.0               0                0              1
4  40.0      NaN               0                1              0
5  35.0  58000.0               1                0              0
6   NaN  52000.0               0                0              1
7  48.0  79000.0               1                0              0
8  50.0  83000.0               0                1              0
9  37.0  67000.0               1                0              0

In [44]:
xnew.duplicated() 

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [46]:
xnew.loc[10]=[37.0,67000.0,1,0,0] 
xnew

Age   Salary  Country_France  Country_Germany  Country_Spain
0   44.0  72000.0             1.0              0.0            0.0
1   27.0  48000.0             0.0              0.0            1.0
2   30.0  54000.0             0.0              1.0            0.0
3   38.0  61000.0             0.0              0.0            1.0
4   40.0      NaN             0.0              1.0            0.0
5   35.0  58000.0             1.0              0.0            0.0
6    NaN  52000.0             0.0              0.0            1.0
7   48.0  79000.0             1.0              0.0            0.0
8   50.0  83000.0             0.0              1.0            0.0
9   37.0  67000.0             1.0              0.0            0.0
10  37.0  67000.0             1.0              0.0            0.0

In [48]:
xnew.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [50]:
xnew.duplicated().sum()

1

In [54]:
xnew.drop_duplicates(inplace=True)

In [55]:
xnew

Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0             1.0              0.0            0.0
1  27.0  48000.0             0.0              0.0            1.0
2  30.0  54000.0             0.0              1.0            0.0
3  38.0  61000.0             0.0              0.0            1.0
4  40.0      NaN             0.0              1.0            0.0
5  35.0  58000.0             1.0              0.0            0.0
6   NaN  52000.0             0.0              0.0            1.0
7  48.0  79000.0             1.0              0.0            0.0
8  50.0  83000.0             0.0              1.0            0.0
9  37.0  67000.0             1.0              0.0            0.0